config/routes.rb
Rails.application.routes.draw do
  
  root "users#login"
  
  get "/users/login" => "users#login", :as => "login"
  
  post "/users/login" => "users#login_confirm"

  get "/users/logout" => "users#logout", :as => "logout"
  
  get "/user" => "users#show", :as => "user"
  
  get "/edit_user" => "users#edit", :as => "edit_user"
  
  put "/user" => "users#update"
  
  get "/sorted_items" => "users#sort_items", :as => "items_by_date"
  
  resources :items, :users, :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  validates :name, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt
  
  has_many :items
  has_many :categories
  validates :name, presence: true
  validates :email, presence: true
  
  
  def encrypt_password(unencrypted_password)
    self.password = BCrypt::Password.create(unencrypted_password)
  end
  
  def correct_password?(attempted_password)
    BCrypt::Password.new(self.password) == attempted_password
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def check_login
    if session[:user_id] == nil
      redirect_to new_user_path
    else
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_login
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to user_path
    else
      render "new"
    end
  end
  
  def index
    @categories = User.find(session[:user_id]).categories
  end
  
  def edit
    @category = Category.find(params[:id])
    @user = User.find(session[:user_id])
  end
  
  def update
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to user_path
    else
      render "edit"
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to user_path
  end
  
  def show
    @category = Category.find(params[:id])
    @items = @category.items
  end
  
  
  
  private
  
  def category_params
    params[:category].permit(:name, :user_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_login
  def index
    @categories = @user.categories
    @items = @user.items
  end
  
  def new
    @categories = @user.categories
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      @user.items << @item
      redirect_to user_path
    else
      render "new"
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @categories = User.find(session[:user_id]).categories
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      redirect_to user_path
    else
      render "edit"
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_path
  end
  
  def show
    @item = Item.find(params[:id])
  end

  private
  
  def item_params
    params[:item].permit(:name, :content, :user_id, :category_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, except: [:new, :create, :login, :login_confirm]
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params_and_password)
    @user.encrypt_password(params[:user][:password])
    if @user.save
      redirect_to users_path
    else
      render "new"
    end
  end
  
  def edit
    # @user = User.find(session[:user_id]) - from before_action
  end
  
  def update
    # @user = User.find(session[:user_id]) - from before_action
    if params[:user][:password] != "" && BCrypt::Password.new(@user.password) != params[:user][:password]
      @user.encrypt_password(params[:user][:password])
      params[:user][:password] = @user.password
      if @user.update_attributes(user_params_and_password)
        redirect_to user_path
      else
        render "edit"
      end
    else
      if @user.update_attributes(user_params)
        redirect_to user_path
      else
        render "edit"
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to user_path
  end
  
  def show
    # @user = User.find(session[:user_id]) - from before_action
    @items = @user.items
    @categories = @user.categories
  end
  
  def login
  end
  
  def login_confirm
    @user = User.find_by(email: params[:user][:email])
    if @user.correct_password?(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path
    else
      render "login"
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to users_path
  end
  
  def sort_items
    @items = @user.items.order(:created_at)
    @categories = @user.categories
  end
  
  private
  
  def user_params
    params[:user].permit(:name, :email)
  end
  def user_params_and_password
    params[:user].permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h2>
  Edit this category
</h2>

<%= form_tag category_path(@category.id), :method => "put" do %>
  <input type="text" name="category[name]" value="<%= @category.name %>">
  <input type="hidden" name="category[user_id]" value="<%= session[:user_id] %>">
  <input type="submit" value="Edit this category">
<% end %>

app/views/categories/index.html.erb
<h1>
  Manage Categories
</h1>


<p>
  <a href="<%= new_category_path %>">Add a new category</a>
</p>

<ul>
  <% @categories.each do |category| %>
    <li>
      <a href="<%= category_path(category.id) %>">
        <%= category.name %>
      </a>
      <p>
        <a href="<%= edit_category_path(category.id) %>">
          Edit this category
        </a>
        <a href="<%= category_path(category.id) %>" data-method="delete">
          Delete this category
        </a>
      </p>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h2>
  Add a new todo list category
</h2>

<%= form_tag categories_path do %>
  <input type="text" name="category[name]">
  <input type="hidden" name="category[user_id]" value="<%= session[:user_id] %>">
  <input type="submit" value="Add new category">
<% end %>

app/views/categories/show.html.erb
<h2>
  <%= @category.name %>
</h2>

<% @items.each do |item| %>
    <h4>
      <a href="<%= item_path(item.id) %>"><%= item.name %></a>
    </h4>
    <p>
      <a href="<%= edit_item_path(item.id) %>">Edit this item</a>
      <a href="<%= item_path(item.id) %>" data-method="delete">Delete this item</a>
    </p>
<% end %>

app/views/items/edit.html.erb
<h3>
  Edit this todo list item
</h3>

<%= form_tag item_path(@item.id), :method => "put" do %>
  <input type="text" name="item[name]" value="<%= @item.name %>">
  <select name="item[category_id]">
    <option>
      -uncategorized-
    </option>
    <% @categories.each do |category| %>
      <option value="<%= category.id %>" <% if @item.category_id == category.id %>selected<% end %>>
        <%= category.name %> 
      </option>
    <% end %>
  </select>
  <textarea name="item[content]"><%= @item.content %></textarea>
  <input type="submit" value="Edit this item">
<% end %>

app/views/items/index.html.erb
<h4>
  <a href="<%= new_item_path %>">
    Add a new item to your todo list
  </a>
</h4>

<% @categories.each do |category| %>
  <h3>
    <%= category.name %>
      <% @items.each do |item| %>
        <% if item.category_id == category.id %>
          <h4>
            <a href="<%= item_path(item.id) %>"><%= item.name %></a>
          </h4>
        <% end %>
      <% end %>
    <% end %>
</h3>
<h3>
  Uncategorized
  <% @items.each do |item| %>
    <% if item.category_id == 0 %>
      <h4>
        <a href="<%= item_path(item.id) %>"><%= item.name %></a>
      </h4>
      <p>
        <a href="<%= edit_item_path(item.id) %>">Edit this item</a>
        <a href="<%= item_path(item.id) %>" data-method="delete">Delete this item</a>
      </p>
    <% end %>
  <% end %>
</h3>

app/views/items/new.html.erb
<h3>
  Add a new todo list item
</h3>

<%= form_tag items_path do %>
  <input type="text" name="item[name]" placeholder="Item name">
  <select name="item[category_id]">
    <option value="nil">
      -uncategorized-
    </option>
    <% @categories.each do |category| %>
      <option value="<%= category.id %>">
        <%= category.name %> 
      </option>
    <% end %>
  </select>
  <textarea name="item[content]" placeholder="Item description"></textarea>
  <input type="submit" value="Add this item">
<% end %>

app/views/items/show.html.erb
<h3>
  <%= @item.name %>
</h3>
<h4>
  <% if @item.category != nil %>
    <%= @item.category.name %>
  <% else %>
    Uncategorized
  <% end %>
</h4>
<p>
  <%= @item.content %>
</p>

<p>
  <a href="<%= edit_item_path(@item.id) %>">Edit this item</a>
  <a href="<%= item_path(@item.id) %>" data-method="delete">Delete this item</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <header>
    <% if session[:user_id] != nil %>
    <% @user_logged_in = User.find(session[:user_id])%>
    <p>You are logged in as <%= @user_logged_in.name %></p>
    <a href="<%= logout_path %>" >Logout</a>
    <% else %>
    <a href="<%= login_path %>">Please log in</a>
    <% end %>
  </header>

<%= yield %>

<footer>
  <a href="<%= user_path %>">Back to my profile</a>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<h3>
  Edit <%= @user.name %>
</h3>

<%= form_tag user_path, :method => "put" do %>
  <input type="text" name="user[name]" value="<%= @user.name %>">
  <input type="text" name="user[email]" value="<%= @user.email %>">
  <input type="password" name="user[password]" placeholder="change password?">
  <input type="submit" value="Edit this user">
<% end %>

app/views/users/index.html.erb
<h2>
  Viewing all users
</h2>

<a href="<%= new_user_path %>">
  Add a user
</a>

<% @users.each do |user| %>
  <h3>
    <a href="<%= user_path(user.id) %>">
      <%= user.name %>
    </a>
  </h3>
  <p>
    <a href="<%= edit_user_path(user.id) %>">
      Edit this user
    </a>
    <a href="<%= user_path(user.id) %>" data-method="delete">
      Delete this user
    </a>
  </p>
<% end %>
  

app/views/users/login.html.erb
<h2>
  Please log in
</h2>
<%= form_tag login_path, :method => "post" do %>
  <input type="text" name="user[email]" placeholder="Email">
  <input type="password" name="user[password]" placeholder="Password">
  <input type="submit" value="Log In">
<% end %>

Still need to register? Click <%= link_to "here", new_user_path %>.

app/views/users/new.html.erb
<h3>
  Add a new user
</h3>

<%= form_tag users_path do %>
  <input type="text" name="user[name]" placeholder="Name">
  <input type="text" name="user[email]" placeholder="Email">
  <input type="password" name="user[password]" placeholder="Password">
  <input type="submit" value="Add this user">
<% end %>

app/views/users/show.html.erb
<h3>
  <%= @user.name %>
</h3>
<p>
  Email - <%= @user.email %>
</p>
<p>
  <a href="<%= edit_user_path %>">
    Edit this user
  </a>
  <br>
  <a href="<%= user_path(@user.id) %>" data-method="delete">
    Delete this user
  </a>
</p>

<p>
  <a href="<%= categories_path %>">
    Manage categories
  </a>
</p>

<p>
  <a href="<%= new_item_path %>">Add a todo item</a>
</p>
<br>
<a href="<%= items_by_date_path %>">
  See items chronologically
</a>
<hr>
<% @categories.each do |category| %>
  <div id="category_<%= category.id %>">
    <h3>
      <%= category.name %>
    </h3>
    <% @items.each do |item| %>
      <% if item.category_id == category.id %>
        <h4>
          <input type="checkbox" id="item<%= item.id %>" value="<%= item.id %>">
          <a href="<%= item_path(item.id) %>"><%= item.name %></a>
        </h4>
      <% end %>
    <% end %>
  </div>
<% end %>
<h3>
Uncategorized
</h3>
<% @items.each do |item| %>
  <% if item.category_id == 0 %>
    <h4>
      <input type="checkbox" id="item<%= item.id %>" value="<%= item.id %>" class="checkbox_for_item">
      <a href="<%= item_path(item.id) %>"><%= item.name %></a>
    </h4>
  <% end %>
<% end %>





<!-- <ul>
  <% @items.each do |item| %>
    <li>
      <a href="<%= item_path(item.id) %>"><%= item.name %></a>
      <p>
        <a href="<%= edit_item_path(item.id) %>">Edit this item</a>
        <a href="<%= item_path(item.id) %>" data-method="delete">Delete this item</a>
      </p>
    </li>
  <% end %>
</ul> -->

app/views/users/sort_items.html.erb
<h3>
  <%= @user.name %>
</h3>
<p>
  Email - <%= @user.email %>
</p>
<p>
  <a href="<%= edit_user_path %>">
    Edit this user
  </a>
  <br>
  <a href="<%= user_path(@user.id) %>" data-method="delete">
    Delete this user
  </a>
</p>

<p>
  <a href="<%= categories_path %>">
    Manage categories
  </a>
</p>

<p>
  <a href="<%= new_item_path %>">Add a todo item</a>
</p>

<a href="<%= user_path %>">
  See items by category
</a>
<hr>
<% @items.each do |item| %>
  <input type="checkbox" id="item<%= item.id %>" value="<%= item.id %>">
  <a href="<%= item_path(item.id) %>"><%= item.name %></a>
  <br>
  <%= item.created_at.to_s(format = :short) %>
  <hr>
<% end %>      


<!-- <ul>
  <% @items.each do |item| %>
    <li>
      <a href="<%= item_path(item.id) %>"><%= item.name %></a>
      <p>
        <a href="<%= edit_item_path(item.id) %>">Edit this item</a>
        <a href="<%= item_path(item.id) %>" data-method="delete">Delete this item</a>
      </p>
    </li>
  <% end %>
</ul> -->